# Julia Problem Sheet

This problem sheet is designed to test some basic Julia
knowledge. Note each problem has multiple solutions, and the solution
sheet will show different ways of solving the same problem.

In assessment, _any_ "solution" will be accepted provided it does the right thing!
So you do not need to be able to write broadcasting or comprehensions
if you can do for loops.



## Array creation and broadcasting

**Problem** Create a vector of length 5 whose entries are `Int` which is
zero in all entries. 

**SOLUTIONS**

In [1]:
zeros(Int, 5)

5-element Vector{Int64}:
 0
 0
 0
 0
 0

In [2]:
fill(0, 5)

5-element Vector{Int64}:
 0
 0
 0
 0
 0

In [3]:
[0 for k=1:5]

5-element Vector{Int64}:
 0
 0
 0
 0
 0

**Problem** Create a 5×6 matrix whose entries are `Int` which is
one in all entries.

**SOLUTIONS**

1. For-loop:

In [4]:
ret = zeros(Int, 5, 6)
for k=1:5, j=1:6
    ret[k,j] = 1
end
ret

5×6 Matrix{Int64}:
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1

2. Ones:

In [5]:
ones(Int, 5, 6)

5×6 Matrix{Int64}:
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1

3. Fill:

In [6]:
fill(1, 5, 6)

5×6 Matrix{Int64}:
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1

4. Comprehension

In [7]:
[1 for k=1:5, j=1:6]

5×6 Matrix{Int64}:
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1

**Problem** Create a 1 × 5 `Matrix{Int}` with entries `A[k,j] = j`.

1. For-loop

In [8]:
A = zeros(Int, 1, 5)
for j = 1:5
    A[1,j] = j
end

2. Comprehension

In [9]:
[j for k=1:1, j=1:5]

1×5 Matrix{Int64}:
 1  2  3  4  5

3. convert transpose:

In [10]:
# Note: (1:5)' is a "row-vector" which behaves differently than a matrix
Matrix((1:5)')

1×5 Matrix{Int64}:
 1  2  3  4  5

**Problem** Create a vector of length 5 whose entries are `Float64`
approximations of `exp(-k)`. (Two solutions: one using a for loop and
one using broadcasting.)

**SOLUTIONS**

1. For-loop

In [11]:
v = zeros(5) # defaults to Float64
for k = 1:5
    v[k] = exp(-k)
end

2. Broadcast:

In [12]:
exp.(-(1:5))

5-element Vector{Float64}:
 0.36787944117144233
 0.1353352832366127
 0.049787068367863944
 0.01831563888873418
 0.006737946999085467

3. Explicit broadcsat:

In [13]:
broadcast(k -> exp(-k), 1:5)

5-element Vector{Float64}:
 0.36787944117144233
 0.1353352832366127
 0.049787068367863944
 0.01831563888873418
 0.006737946999085467

4. Comprehension:

In [14]:
[exp(-k) for k=1:5]

5-element Vector{Float64}:
 0.36787944117144233
 0.1353352832366127
 0.049787068367863944
 0.01831563888873418
 0.006737946999085467

**Problem** Create a 5 × 6 matrix `A` whose entries `A[k,j] == cos(k+j)`.
 (Two solutions: one using a for loop and
one using broadcasting.)

**SOLUTIONS**

1. For-loop:

In [15]:
A = zeros(5,6)
for k = 1:5, j = 1:6
    A[k,j] = cos(k+j)
end
A

5×6 Matrix{Float64}:
 -0.416147  -0.989992  -0.653644   0.283662   0.96017    0.753902
 -0.989992  -0.653644   0.283662   0.96017    0.753902  -0.1455
 -0.653644   0.283662   0.96017    0.753902  -0.1455    -0.91113
  0.283662   0.96017    0.753902  -0.1455    -0.91113   -0.839072
  0.96017    0.753902  -0.1455    -0.91113   -0.839072   0.0044257

2. Broadcasting:

In [16]:
k = 1:5
j = 1:6
cos.(k .+ j')

5×6 Matrix{Float64}:
 -0.416147  -0.989992  -0.653644   0.283662   0.96017    0.753902
 -0.989992  -0.653644   0.283662   0.96017    0.753902  -0.1455
 -0.653644   0.283662   0.96017    0.753902  -0.1455    -0.91113
  0.283662   0.96017    0.753902  -0.1455    -0.91113   -0.839072
  0.96017    0.753902  -0.1455    -0.91113   -0.839072   0.0044257

3. Broadcasting (explicit):

In [17]:
broadcast((k,j) -> cos(k+j), 1:5, (1:6)')

5×6 Matrix{Float64}:
 -0.416147  -0.989992  -0.653644   0.283662   0.96017    0.753902
 -0.989992  -0.653644   0.283662   0.96017    0.753902  -0.1455
 -0.653644   0.283662   0.96017    0.753902  -0.1455    -0.91113
  0.283662   0.96017    0.753902  -0.1455    -0.91113   -0.839072
  0.96017    0.753902  -0.1455    -0.91113   -0.839072   0.0044257

## Types